language: c
compiler:
  - clang
  - gcc
script:
  - git submodule update --init
  - ln -s ../libatomic_ops bdwgc/libatomic_ops
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - make
  - make crisp_fuzz
  - ./crisp < tests.crisp | tee test.log
  - (! grep -v pass test.log)
  - ./crisp < modules/queue/test.crisp
  - ./crisp < modules/map/test.crisp
  - ./crisp < examples/libc_demo.crisp
  - ./crisp < examples/rank_select.crisp
  - ./crisp < examples/binzipper.crisp
  - ./crisp < examples/benchmark.crisp
