language: c
compiler:
  - clang
  - gcc
script:
  - git submodule update --init
  - ln -s ../libatomic_ops bdwgc/libatomic_ops
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - make
  - cat stdlib.crisp tests.crisp | ./crisp | tee test.log
  - (! grep -v pass test.log)
  - cat stdlib.crisp libc_demo.crisp | ./crisp
  - make crisp_fuzz
  - cat stdlib.crisp benchmark.crisp | ./crisp_fuzz
